#!/usr/bin/env python
import os
import wget
import requests
import json


TOKEN = 'insert your token here'
#using secondary Raspberry Pi to broker communications and have a repo of images
output_directory = '/home/pi/farm/pics'
headers = {'Authorization': 'Bearer ' + TOKEN,
           'content-type': "application/json"}
response = requests.get('https://my.farmbot.io/api/images', headers=headers)
images = response.json()
most_recent_image_url = images[0]['attachment_url']
url = most_recent_image_url
filename = wget.download(url,out = output_directory)
